theme: just-the-docs
#theme: jekyll-theme-minimal
title: openClimbingMap
description: Werde Teil der openClimbingMap-Community!
remote_theme: pmarsceill/just-the-docs



# Navigation
header_pages:
  - index.md
  - team.md
  - features.md
  - installation.md